# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: Test the Action

on:
  # run pipeline on push event of main branch
  push:
    branches:
      - main
  # run pipeline on pull request
  pull_request:
  # run pipeline on merge queue
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test-action
  cancel-in-progress: true

jobs:
  test-pgm-version-bump:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set PyPI Version
        uses: PowerGridModel/pgm-version-bump@

      - name: Low latest version
        run: cat PYPI_VERSION
